export const gloryItemData = [
  {
    title: "Martial Artists",
    comment: "Beyond the Mat, Building a Legacy",
    description: "IRONWILL empowers martial artists to build sustainable careers, offering multiple revenue streams, fan engagement, and a platform to reach their full potential.",
    features: [
      {
        title:"Sponsorships & Donations,",
        desc:"handle all aspects of sponsorship through our platform with ease, from receiving donations to managing complex revenue-sharing agreements."
      },
      {
        title:"Paid content,",
        desc:"simplify the process of creating and showcasing unique content. Offer anything from exclusive training programs to insights and behind-the-scenes video's."
      },
      {
        title:"Merchandise,",
        desc:"we provide all the tools and resources you need to build, launch and sell your own merchandise brand."
      },
      {
        title:"Matches, ",
        desc:"organize RL matches. Set up matches yourself or let your fans or another facilitator do it. Earn prize money and get your share of the ticket revenue."
      },
      {
        title:"RL training, ",
        desc:"leverage your expertise by offering personalized training and/or coaching at IRONWILL's bootcamp campuses."
      },
      {
        title:"Accountancy, ",
        desc:"handle everything you do through our easy accounting function which simplifies financial management."
      },
    ],
  },
  {
    title: "Fans",
    comment: "Fans become partners",
    description: "IRONWILL offers more than just watching; it's about being part of the action. Become an active participant and shape the future of your favorite martial artists, reaping the rewards of their success.",
    features: [
      {
        title:"Sponsor & Invest, ",
        desc:"become an active investor and share in the revenue generated by your favorite martial artists through innovative revenue-sharing sponsorship models."
      },
      {
        title:"Manage, ",
        desc:"manage your investments with our innovative tools and become a talent manager yourself."
      },
      {
        title:"Donate, ",
        desc:"propose compelling match-ups and organize matches togheter with other fans and facilitators."
      },
      {
        title:"Matches, ",
        desc:"organize RL matches. Set up matches yourself or let your fans or another facilitator do it. Earn prize money and get your share of the ticket revenue."
      },
      {
        title:"Bet, ",
        desc:" use our safe and secure platform to bet on the outcome of matches organized on IRONWILL."
      },
      {
        title:"Rewards, ",
        desc:"become an active participant on the platform and earn points and FICCO coins."
      },
    ],
  },
  {
    title: "Venues",
    comment: "From seats to spectacles",
    description: "IRONWILL facilitates event and match hosting that drives ticket sales and pay-per-view purchases.",
    features: [
      {
        title:"Events & Organization, ",
        desc:"host/organize events and make your venue available for matches organized trough our platform."
      },
      {
        title:"Tickets, ",
        desc:"earn money by selling tickets for events and matches organized by your organization."
      },
      {
        title:"Match making, ",
        desc:"arrange and manage fights and events, including fighter selection, scheduling, and logistical coordination."
      },
      {
        title:"Sponsorships, ",
        desc:"attract sponsorships to secure financial support for events."
      },
    ],
  },
  {
    title: "Brands",
    comment: "Unleash your brand's potential",
    description: "IRONWILL empowers brands to reach a passionate audience, boosting brand awareness and engagement while product sales through the platform provides a direct revenue model.",
    features: [
      {
        title:"Sponsorships,",
        desc:"offer a variety of sponsorship opportunities to talents, from traditional endorsements to revenue-sharing models."
      },
      {
        title:"Advertisement,",
        desc:"targeted advertising opportunities for brands, allowing brands to reach a passionate audience of fight fans and to directly connect with potential customers."
      },
      {
        title:"Sell,",
        desc:"use our direct-to-consumer sales platform to sell your products to a dedicated audience."
      },
      {
        title:"Organize, ",
        desc:"co-organize matches and enhance marketing reach while generating unique brand experiences."
      },
    ],
  },
  {
    title: "Clubs",
    comment: "From training mats to triumph",
    description: "IRONWILL makes it easy for clubs to thrive, gain new members and drive engagement with a passionate audience, all while we handle the back-office operations.",
    features: [
      {
        title:"Manage,",
        desc:"handle all aspects of managing your martial arts club through our platform, from accountancy and member oversight to marketing."
      },
      {
        title:"Match making, ",
        desc:"arrange and manage fights and events, including fighter selection, scheduling, and logistical coordination."
      },
      {
        title:"Accept matches,",
        desc:"accept matches proposed and funded by martial artists and fans."
      },
      {
        title:"Events & Organization, ",
        desc:"host/organize events and make your venue available for matches organized through our platform."
      },
      {
        title:"Merchandise, ",
        desc:"we provide all the tools and resources you might need to launch and build your own merchandise brand."
      },
      {
        title:"Sponsors, ",
        desc:"easily find sponsors for your club."
      },
      {
        title:"New members, ",
        desc:"find new members through our platform."
      },
      {
        title:"Tickets, ",
        desc:"earn money by selling tickets for events and matches organized by your organization."
      },
    ],
  },
  {
    title: "Promoters",
    comment: "Connect, promote, succeed",
    description: "IRONWILL provides the tools to streamline operations, expand reach, and maximize profits, ensuring promoters can focus on delivering unforgettable fight experiences.",
    features: [
      {
        title:"Match making,",
        desc:"arrange and manage fights and events, including fighter selection, scheduling, and logistical coordination."
      },
      {
        title:"Sponsorships,",
        desc:"attract sponsorships to secure financial support for events."
      },
      {
        title:"Share,",
        desc:"offer investors a stake in events or fighters in exchange for financial backing, sharing in the profits and growth of the venture."
      },
      {
        title:"Tickets, ",
        desc:"utilize our platform to sell tickets and PPV access to events, maximizing reach and revenue potential."
      },
      {
        title:"Live streaming, ",
        desc:"use our robust live streaming platform, allowing fans to experience the thrill in real-time."
      },
    ],
  },

];
